# Python CircleCI 2.1 configuration file
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7
        environment:
          PIPENV_VENV_IN_PROJECT: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
        name: install dependencies
        command: |
          sudo pip installpipenv
          pipenv install
      - run:
        name: run tests
          pipenv run flake8 --exclude=.venv --statistics 
          pipenv run pytest -v --cov-config .coveragerc --cov=calculator -W ignore::DeprecationWarning  
