# Python CircleCI 2 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
        environment:
          PIPENV_VENV_IN_PROJECT: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            pipenv install
            pipenv graph
      - run:
          name: run tests
          command: |
            pipenv run flake8 --exclude=.venv --statistics
            pipenv run pytest -v --cov-config=.coveragerc --cov=calculator -W ignore::DeprecationWarning